### ISSUE TITLE
[STORY]: Game Scoring System

### ISSUE THREAD

**Issue by misrule** [misrule/hangman#8]
As a user, I want a realtime, quantitative measure of my performance in the current session. And I want to see my best historical best performance so that I can tell if I'm getting better or not over time.

### Tasks
- [ ] Design scoring weights and metrics
- [ ] Implement persistence for high-score
- [ ] Add score presentation UI
